main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import static
from django.conf import settings
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #ruta para establecer idioma
    path('i18n/', include('django.conf.urls.i18n')),
    #path('', TemplateView.as_view(template_name='main/index.html'), name='welcome'),
    path('', views.ListadoEventos.as_view(), name='listadoEventos'),
    path('main/perfil/', views.PerfilCliente.as_view(), name='perfil'),
    path('main/registro/', views.Registro.as_view(), name='registro'),
    path('main/cerrarSesion/', views.CerrarSesion.as_view(), name='cerrarSesion'),
    path('main/iniciarSesion/', views.IniciarSesion.as_view(), name='iniciarSesion'),
    path('main/agregarPerfil/', views.AgregarPerfil.as_view(template_name='main/agregarPerfil.html'), name='agregarPerfil'),
    path('main/editarPerfil/<int:pk>', views.EditarPerfil.as_view(template_name='main/editarPerfil.html'), name='editarPerfil'),
    path('main/eliminarPerfil/<int:pk>', views.EliminarPerfil.as_view(template_name='main/eliminar.html'), name='eliminarPerfil'),
    path('main/eventoDetalle/<int:pk>', views.EventoDetalle.as_view(), name='eventoDetalle'),
    path('PanelAdmin/panelAdmin/', views.PanelAdmin.as_view(), name='panelAdmin'),
    path('PanelAdmin/administrarSala/<int:pk>', views.AdministrarSala.as_view(), name='administrarSala'),
    path('PanelAdmin/administrarEvento/<int:pk>', views.AdministrarEvento.as_view(), name='administrarEvento'),
    path('PanelAdmin/agregarSala/', views.AgregarSala.as_view(template_name='PanelAdmin/agregarSala.html'), name='agregarSala'),
    path('PanelAdmin/editarSala/<int:pk>', views.EditarSala.as_view(template_name='PanelAdmin/editarSala.html'), name='editarSala'),
    path('PanelAdmin/eliminarSala/<int:pk>', views.EliminarSala.as_view(template_name='PanelAdmin/eliminar.html'), name='eliminarSala'),
    path('PanelAdmin/agregarEvento/', views.AgregarEvento.as_view(template_name='PanelAdmin/agregarEvento.html'), name='agregarEvento'),
    path('PanelAdmin/editarEvento/<int:pk>', views.EditarEvento.as_view(template_name='PanelAdmin/editarEvento.html'), name='editarEvento'),
    path('PanelAdmin/eliminarEvento/<int:pk>', views.EliminarEvento.as_view(template_name='PanelAdmin/eliminar.html'), name='eliminarEvento'),
    path('PanelAdmin/asignarPrecioZonaEvento/', views.AsignarPrecioZonaEvento.as_view(template_name='PanelAdmin/asignarPrecioZonaEvento.html'), name='asignarPrecioZonaEvento'),
    path('main/paypal/', views.Paypal.as_view(template_name='main/paypal.html'), name='paypal'),
    path('main/pago/', views.pago, name= 'pago'),
    # path('main/generar_pdf/', views.generar_pdf, name='generar_pdf'),
    path('main/resumenCompra/', views.ResumenCompra.as_view(template_name='main/resumenCompra.html'), name='resumenCompra'),
    path('main/compraDetalle/<int:pk>', views.CompraDetalle.as_view(template_name='main/resumenCompra.html'), name='compraDetalle'),
    path('PanelAdmin/Top5clientes/', views.Top5clientes.as_view(), name='top5clientes'),
    path('PanelAdmin/ComprasPorUsuario/', views.ComprasPorUsuario.as_view(), name='comprasPorUsuario'),



  ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.conf import settings
from django.db import models

# Create your models here.

class Perfil(models.Model):
    nombre = models.CharField(max_length=30)
    dni = models.CharField(max_length=9)
    fecha_nac = models.DateField()
    direccion = models.CharField(max_length=30)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT)

    def __str__(self):
        return str(self.nombre)

class Sala(models.Model):
    nombre = models.CharField(max_length=10)
    mapa = models.ImageField(upload_to='main/imagenes/')
    aforo = models.IntegerField()

    def __str__(self):
        return 'Id: %s Nombre: %s Mapa: %s Aforo: %s' % (self.id, self.nombre, self.mapa, self.aforo)


class Zona(models.Model):
    sala = models.ForeignKey(Sala, on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=10)
    aforo = models.IntegerField()

    def __str__(self):
        return 'Sala: %s Nombre: %s Id: %s Aforo: %s' % (self.sala, self.nombre, self.id, self.aforo)

class Asiento(models.Model):
    zona = models.ForeignKey(Zona, on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=10)

    def __str__(self):
        return 'Zona: %s Nombre: %s Id: %s' % (self.zona, self.nombre, self.id)

class Evento(models.Model):
    nombre = models.CharField(max_length=10)
    imagen = models.ImageField(upload_to='main/imagenes/')
    fecha_hora = models.DateTimeField()
    disponibles = models.IntegerField()
    sala = models.ForeignKey(Sala, on_delete=models.RESTRICT)

    def __str__(self):
        return 'ID: %s Nombre: %s Fecha: %s Imagen: %s' % (self.id, self.nombre, self.fecha_hora, self.imagen)

class Zona_evento(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.RESTRICT)
    zona = models.ForeignKey(Zona, on_delete=models.RESTRICT)
    disponibles = models.IntegerField()
    precio = models.FloatField()

    def __str__(self):
        return 'ID: %s Zona: %s Evento: %s Disponibles: %s Precio: %s' % (self.id, self.zona, self.evento, self.disponibles, self.precio)

class Asiento_evento(models.Model):
    zona_evento = models.ForeignKey(Zona_evento, on_delete=models.RESTRICT)
    asiento = models.ForeignKey(Asiento, on_delete=models.RESTRICT)
    estado = models.BooleanField()
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, null=True)

    def __str__(self):
        return 'ID: %s Zona: %s Asiento: %s' % (self.id, self.zona_evento, self.asiento)


class Compra_total(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, null=True)
    fecha_hora = models.DateTimeField()
    zona_evento = models.ForeignKey(Zona_evento, on_delete=models.RESTRICT)
    total = models.FloatField()

    def __str__(self):
        return 'ID: %s usuario: %s fecha_hora: %s zona_evento: %s total: %s' % (self.id, self.usuario, self.fecha_hora, self.zona_evento, self.total)
class Compra_asiento(models.Model):
    asiento_evento = models.ForeignKey(Asiento_evento, on_delete=models.RESTRICT)
    compra = models.ForeignKey(Compra_total, on_delete=models.RESTRICT)

    def __str__(self):
        return 'ID: %s Asiento: %s Compra: %s' % (self.id, self.asiento_evento, self.compra)

main/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class UnidadesForm(forms.Form):
    unidades = forms.IntegerField(required=True, min_value=1)

class SalaForm(forms.ModelForm):
    class Meta:
        model = Sala
        fields = '__all__'

class ZonaForm(forms.ModelForm):
    class Meta:
        model = Zona
        fields = '__all__'

class AsientoForm(forms.ModelForm):
    class Meta:
        model = Asiento
        fields = '__all__'

class EventoForm(forms.ModelForm):
    class Meta:
        model = Evento
        fields = ['nombre', 'imagen', 'fecha_hora', 'sala']

main/views.py
from datetime import date, datetime

import pytz
from cffi.backend_ctypes import unicode
from django.contrib.sessions import serializers

from django.db.models import Q, Count, Sum
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, resolve
from django.views import View
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, ListView

from main.forms import UnidadesForm, EventoForm, SalaForm
from main.models import *

from django.db import transaction
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import *
from django.contrib.auth import login, logout, authenticate
from django.core.serializers.json import DjangoJSONEncoder
from django.core import serializers
from django.core.serializers import serialize

from paypalcheckoutsdk.orders import OrdersGetRequest, OrdersCaptureRequest
from paypalcheckoutsdk.core import PayPalHttpClient, SandboxEnvironment
import sys, json
from reportlab.pdfgen import canvas
from django.http import HttpResponse



# Create your views here.


"""Serializar objetos de la clase Asiento_evento en formato JSON"""
class LazyEncoder(DjangoJSONEncoder):
    """Si el objeto es una instancia de esa clase, devuelve su representación en formato string"""
    def default(self, obj):
        if isinstance(obj, Asiento_evento):
            return str(obj)
        return super().default(obj)

"""Serializar int y float en formato JSON"""
class CustomEncoder(json.JSONEncoder):
    """Si el objeto es de tipo int o float, devuelve su representación en formato string"""
    def default(self, obj):
        if isinstance(obj, int) or isinstance(obj, float):
            return str(obj)
        raise TypeError("No se puede serializar el objeto")

"""REGISTRO, LOGIN Y LOGOUT"""
class Registro(CreateView):
    template_name = 'main/registro.html'
    form_class = UserCreationForm
    def get_success_url(self):
        return reverse('welcome')

    @transaction.atomic
    def post(self, request, *args, **kwargs):

            if request.POST['password1'] == request.POST['password2']:
                try:
                    user = User.objects.create_user(username=request.POST['username'],
                                                    password=request.POST['password1'])
                    user.save()

                    login(request, user)
                    return redirect('listadoEventos')
                except:
                    return render(request, "main/registro.html",
                                  {'form': UserCreationForm, 'error': 'El usuario ya existe'})
            return render(request, "main/registro.html",
                          {'form': UserCreationForm, 'error': 'Las contraseñas no coinciden'})

class CerrarSesion(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('listadoEventos')

class IniciarSesion(View):
    def get(self, request, *args, **kwargs):
        form = AuthenticationForm()
        return render(request, 'main/iniciarSesion.html', {'form': AuthenticationForm})

    def post(self, request, *args, **kwargs):
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'main/iniciarSesion.html', {'form': AuthenticationForm, 'error': 'El usuario o la contraseña son incorrectos'})
        else:
            login(request, user)
            return redirect('listadoEventos')


"""PERFIL DE USUARIO"""
class PerfilCliente(TemplateView):
    template_name = 'main/perfil.html'
    model= Perfil
    def get(self, request, *args, **kwargs):
        user = request.user
        num_user = user.id
        perfil = Perfil.objects.filter(usuario_id=num_user)

        compras = Compra_total.objects.filter(usuario=num_user).order_by('id')

        return render(request, self.template_name, {'perfil': perfil, 'compras': compras})

class CompraDetalle(TemplateView):
    template_name = 'main/resumenCompra.html'

    def get(self, request, pk, *args, **kwargs):
        ultimo_pedido = Compra_total.objects.get(id=pk)
        asientos = Compra_asiento.objects.filter(compra=ultimo_pedido.id).order_by('id')

        generar = request.GET.get("pdf", "cero")
        if generar != "cero":
            # Crear la respuesta HTTP con el PDF adjunto
            response = HttpResponse(content_type='application/pdf')
            response['Content-Disposition'] = 'attachment; filename="entradas.pdf"'

            # Generar el contenido del PDF
            buffer = response
            p = canvas.Canvas(buffer)

            evento_nombre = ultimo_pedido.zona_evento.evento.nombre
            precio = "Total: " + str(ultimo_pedido.total) + " €"
            fecha = "Fecha del evento: " + str(ultimo_pedido.zona_evento.evento.fecha_hora)
            sala = "Sala: " + ultimo_pedido.zona_evento.evento.sala.nombre
            zona = "Zona: " + ultimo_pedido.zona_evento.zona.nombre

            for a in asientos:
                # Añadir título al PDF
                p.setFont('Helvetica-Bold', 32)
                p.drawString(70, 720, evento_nombre)

                # Añadir imagen al PDF
                #image_path = '	http://localhost:8000/main/imagenes/marcadeagua.png'
                image_path = '	http://3.216.41.255:9001/imagenes/main/imagenes/marcadeagua.png'
                p.drawImage(image_path, 490, 750, width=80, height=80)

                # Mas contenido
                #image_path = 'http://localhost:8000/' + str(ultimo_pedido.zona_evento.evento.imagen.url)
                image_path = '	http://3.216.41.255:9001/' + str(ultimo_pedido.zona_evento.evento.imagen.url)
                p.drawImage(image_path, 100, 500, width=350, height=200)

                p.setFont('Helvetica', 27)
                p.drawString(70, 460, precio)

                p.setFont('Helvetica', 17)
                p.drawString(70, 420, fecha)

                p.setFont('Helvetica', 17)
                p.drawString(70, 380, sala)

                #image_path = 'http://localhost:8000/' + str(ultimo_pedido.zona_evento.zona.sala.mapa)
                image_path = 'http://3.216.41.255:9001/imagenes/' + str(ultimo_pedido.zona_evento.zona.sala.mapa)
                p.drawImage(str(image_path), 220, 330, width=100, height=70)

                p.setFont('Helvetica', 27)
                p.drawString(70, 280, zona)

                n = a.asiento_evento.asiento.nombre
                p.setFont('Helvetica-Bold', 30)
                p.drawString(70, 180, n)
                #image_path = 'http://localhost:8000/main/imagenes/QR.png'
                image_path = 'http://3.216.41.255:9001/imagenes/main/imagenes/QR.png'
                p.drawImage(image_path, 250, 130, width=130, height=130)

                p.showPage()

            # Finalizar el PDF

            p.save()

            return response

        return render(request, self.template_name, {'ultimo_pedido': ultimo_pedido, 'asientos': asientos})


class AgregarPerfil(CreateView):
    model = Perfil
    template_name = 'main/agregarPerfil.html'
    fields = '__all__'

    def post(self, request, *args, **kwargs):
        nombre = request.POST.get("nombre")
        dni = request.POST.get("dni")
        fecha_nac = request.POST.get("fecha_nac")
        direccion = request.POST.get("direccion")
        user = request.user

        perfil = Perfil.objects.create(nombre=nombre,
                                         dni=dni,
                                         fecha_nac=fecha_nac,
                                         direccion=direccion,
                                         usuario=user)

        perfil.save()
        return redirect('perfil')
    def get_success_url(self):
        return reverse('perfil')

class EditarPerfil(UpdateView):
    model = Perfil
    fields = ['nombre', 'dni', 'fecha_nac', 'direccion']

    def get_success_url(self, **kwargs):
        return reverse('perfil')

class EliminarPerfil(DeleteView):
    model = Perfil
    fields = '__all__'
    def get_success_url(self, *args, **kwargs):
        return reverse('perfil')


"""LISTADO DE EVENTOS Y FILTRADO"""
class ListadoEventos(TemplateView):
    template_name = 'main/index.html'
    def get(self, request, *args, **kwargs):
        evento = Evento.objects.all()

        busqueda = request.GET.get("buscar")
        disponible = request.GET.get("disponibilidad")
        fechaInicio = request.GET.get("fecha")
        fechaFin = request.GET.get("fecha2")

        ahora = datetime.now(pytz.utc)

        if busqueda:

            evento = Evento.objects.filter(nombre__icontains=busqueda)

        if disponible:
            if disponible == '2':
                if fechaInicio:
                    if fechaFin:
                        evento = Evento.objects.filter(fecha_hora__gte = fechaInicio, fecha_hora__lte = fechaFin)
                    else:
                        evento = Evento.objects.filter(fecha_hora__gte = fechaInicio)
                else:
                    if fechaFin:
                        evento = Evento.objects.filter(fecha_hora__lte = fechaFin)
                    else:
                        evento = Evento.objects.all()
            else:
                if fechaInicio:
                    if fechaFin:
                        if disponible == '0':
                            evento = Evento.objects.filter(fecha_hora__gte = fechaInicio, fecha_hora__lte = fechaFin, disponibles = '0')
                        else:
                            evento = Evento.objects.filter(fecha_hora__gte=fechaInicio, fecha_hora__lte=fechaFin,
                                                           disponibles__gt = 0)
                    else:
                        if disponible == '0':

main/templates/PanelAdmin/administrarEvento.html
{% extends 'base.html' %}
<html>
{% block content %}
<div class="container-flex align-items-center">
    <h1 class="text-center">Administrar evento</h1>
      <p></p>

    <table class="table table-hover">
        <tr class="table-info text-center"><td>
        </td></tr>
        <tr class="table-secondary"><td>
        {% for x in zona_evento %}
            <table class="table table-striped">
                <tr class="table-primary">
                    <td><h5 class="text-center">{{ x.zona.nombre }}</h5></td>
                </tr>
                    <tr>
                        <td><p class="text-center">Asientos</p></td>
                    </tr>


                    {% for y in asiento_evento %}
                        {% for z in y %}
                            {% if z.zona_evento.id == x.id %}
                        <tr>
                            <td><h6>{{ z.asiento.nombre }}</h6></td>
                        </tr>
                            {% endif %}
                        {% endfor %}

                    {% endfor %}
                </tr>
            </table>
        {% endfor %}
        </td></tr>
    </table>
</div>
{% endblock %}
</html>

main/templates/PanelAdmin/administrarSala.html
{% extends 'base.html' %}
<html>
{% block content %}
<div class="container-flex align-items-center">
    <h1 class="text-center">Administrar sala</h1>
      <p></p>

    <table class="table table-hover">
        <tr class="table-secondary"><td>
        {% for x in zona %}
            <table class="table table-striped">
                <tr class="table-primary">
                    <td><h5 class="text-center">{{ x.nombre }}</h5></td>
                </tr>
                    <tr>
                        <td><p class="text-center">Asientos</p></td>
                    </tr>

                    {% for y in asiento %}
                        {% for z in y %}
                            {% if z.zona.id == x.id %}
                        <tr>
                            <td><h6>{{ z.nombre }}</h6></td>
                        </tr>
                            {% endif %}
                        {% endfor %}

                    {% endfor %}
                </tr>
            </table>
        {% endfor %}
        </td></tr>
    </table>
</div>
{% endblock %}
</html>

main/templates/PanelAdmin/agregarAsientoEvento.html
    {% block titulo %}    <h1>Insertar un nuevo asiento(en el evento):</h1>  {% endblock %}

    {% block contenido %}
        <style>
            #login-row {
            background-image: linear-gradient(to bottom, #5ee7df 0%, #b490ca 100%);
            }
        </style>
        {% include 'main/form.html' %}

    {% endblock %}

main/templates/PanelAdmin/agregarEvento.html
{% extends 'base.html' %}

{% block content %}
<html>
    <style>
        .hm-gradient {
            background-image: linear-gradient(to top, #f3e7e9 0%, #e3eeff 99%, #e3eeff 100%);
        }
        .darken-grey-text {
            color: #2E2E2E;
        }
        .danger-text {
            color: #ff3547; }
        .default-text {
            color: #2BBBAD;
        }
        .info-text {
            color: #33b5e5;
        }
        .form-white .md-form label {
          color: black;
        }
        .form-white input[type=text]:focus:not([readonly]) {
            border-bottom: 1px solid #fff;
            -webkit-box-shadow: 0 1px 0 0 #fff;
            box-shadow: 0 1px 0 0 #fff;
        }
        .form-white input[type=text]:focus:not([readonly]) + label {
            color: #fff;
        }
        .form-white input[type=password]:focus:not([readonly]) {
            border-bottom: 1px solid #fff;
            -webkit-box-shadow: 0 1px 0 0 #fff;
            box-shadow: 0 1px 0 0 #fff;
        }
        .form-white input[type=password]:focus:not([readonly]) + label {
            color: #fff;
        }
        .form-white input[type=password], .form-white input[type=text] {
            border-bottom: 1px solid #fff;
        }
        .form-white .form-control:focus {
            color: #fff;
        }
        .form-white .form-control {
            color: #fff;
        }
        .form-white textarea.md-textarea:focus:not([readonly]) {
            border-bottom: 1px solid #fff;
            box-shadow: 0 1px 0 0 #fff;
            color: #fff;
        }
        .form-white textarea.md-textarea  {
            border-bottom: 1px solid #fff;
            color: #fff;
        }
        .form-white textarea.md-textarea:focus:not([readonly])+label {
            color: #fff;
        }
        .ripe-malinka-gradient {
            background-image: linear-gradient(120deg, #f093fb 0%, #f5576c 100%);
        }
        .near-moon-gradient {
            background-image: linear-gradient(to bottom, #5ee7df 0%, #b490ca 100%);
        }
    </style>
      <div class="row offset-3 col-12">
                <!-- Grid column -->
                <div class="col-md-6 mb-4">
                    <div class="card near-moon-gradient form-white">
                        <div class="card-body">
                            <!-- Form subscription -->

                    <form enctype="multipart/form-data" method="post">
                     {% csrf_token %}
                     {{ form.as_p }}
                           <h3 class="text-center indigo-text font-bold py-4"><strong>Crear un nuevo evento</strong></h3>
                                <div class="md-form offset-4 col-10">
                                    <label for="id_nombre">Nombre:</label>
                                     <input type="text" name="nombre" maxlength="10" required id="id_nombre">
                                </div><br/>
                                <div class="md-form  offset-4 col-10">
                                    <label for="id_imagen">Imagen:</label>
                                    <input type="file" name="imagen" required id="id_imagen">
                                </div><br/>
                                <div class="md-form  offset-4 col-10">
                                     <label for="id_fecha_hora">Fecha-hora:</label>
                                    <input type="datetime-local" name="fecha_hora" required id="id_fecha_hora">
                                </div><br/>
                                <div class="md-form  offset-4 col-10">
                                     <label for="id_sala">Sala:</label>
                                      <select name="sala" required id="id_sala">
                                          <option value="" selected>---------</option>
                                            {% for x in sala %}
                                            <option value={{x.id}}>{{x.nombre}}</option>

                                            {% endfor %}
                                      </select>
                                </div><br/>
                                <div class="text-center py-4">
                                    <button  type="submit" class="btn btn-info">Crear evento <i class="fa fa-paper-plane-o ml-1"></i></button>
                                </div>
                    </form>

                            <!-- Form subscription -->
                        </div>
                    </div>
                </div>


</html>
{% endblock %}

main/templates/PanelAdmin/agregarSala.html
{% extends 'base.html' %}

{% block content %}
<html>
    <style>
        .hm-gradient {
            background-image: linear-gradient(to top, #f3e7e9 0%, #e3eeff 99%, #e3eeff 100%);
        }
        .darken-grey-text {
            color: #2E2E2E;
        }
        .danger-text {
            color: #ff3547; }
        .default-text {
            color: #2BBBAD;
        }
        .info-text {
            color: #33b5e5;
        }
        .form-white .md-form label {
          color: black;
        }
        .form-white input[type=text]:focus:not([readonly]) {
            border-bottom: 1px solid #fff;
            -webkit-box-shadow: 0 1px 0 0 #fff;
            box-shadow: 0 1px 0 0 #fff;
        }
        .form-white input[type=text]:focus:not([readonly]) + label {
            color: #fff;
        }
        .form-white input[type=password]:focus:not([readonly]) {
            border-bottom: 1px solid #fff;
            -webkit-box-shadow: 0 1px 0 0 #fff;
            box-shadow: 0 1px 0 0 #fff;
        }
        .form-white input[type=password]:focus:not([readonly]) + label {
            color: #fff;
        }
        .form-white input[type=password], .form-white input[type=text] {
            border-bottom: 1px solid #fff;
        }
        .form-white .form-control:focus {
            color: #fff;
        }
        .form-white .form-control {
            color: #fff;
        }
        .form-white textarea.md-textarea:focus:not([readonly]) {
            border-bottom: 1px solid #fff;
            box-shadow: 0 1px 0 0 #fff;
            color: #fff;
        }
        .form-white textarea.md-textarea  {
            border-bottom: 1px solid #fff;
            color: #fff;
        }
        .form-white textarea.md-textarea:focus:not([readonly])+label {
            color: #fff;
        }
        .ripe-malinka-gradient {
            background-image: linear-gradient(120deg, #f093fb 0%, #f5576c 100%);
        }
        .near-moon-gradient {
            background-image: linear-gradient(to bottom, #5ee7df 0%, #b490ca 100%);
        }
    </style>
      <div class="row offset-3 col-12">
                <!-- Grid column -->
                <div class="col-md-6 mb-4">
                    <div class="card near-moon-gradient form-white">
                        <div class="card-body">
                            <!-- Form subscription -->

                    <form enctype="multipart/form-data" method="post">
                     {% csrf_token %}
                     {{ form.as_p }}
                           <h3 class="text-center indigo-text font-bold py-4"><strong>Crear una nueva sala</strong></h3>
                                <div class="md-form offset-4 col-10">
                                    <label for="nombre">Nombre:</label>
                                     <input type="text" name="nombre" maxlength="10" required id="nombre">
                                </div><br/>
                                <div class="md-form  offset-4 col-10">
                                    <label for="mapa">Imagen:</label>
                                    <input type="file" name="mapa" required id="mapa">
                                </div><br/>

                                <div class="md-form offset-4 col-10">
                                    <label for="zona1">Nombre zona 1:</label>
                                     <input type="text" name="zona1" maxlength="10" required id="zona1">
                                </div><br/>
                               <div class="md-form offset-4 col-10">
                                    <label for="aforozona1">Aforo zona 1:</label>
                                     <input type="number" name="aforozona1"  min="1" max="99" required id="aforozona1">
                                </div><br/>

                                 <div class="md-form offset-4 col-10">
                                    <label for="zona2">Nombre zona 2:</label>
                                     <input type="text" name="zona2" maxlength="10" required id="zona2">
                                </div><br/>
                               <div class="md-form offset-4 col-10">
                                    <label for="aforozona2">Aforo zona 2:</label>
                                     <input type="number" name="aforozona2" min="1" max="99" required id="aforozona2">
                                </div><br/>

                                 <div class="md-form offset-4 col-10">
                                    <label for="zona3">Nombre zona 3:</label>
                                     <input type="text" name="zona3" maxlength="10" required id="zona3">
                                </div><br/>
                               <div class="md-form offset-4 col-10">
                                    <label for="aforozona3">Aforo zona 3:</label>
                                     <input type="number" name="aforozona3" min="1" max="99" required id="aforozona3">
                                </div><br/>


                                <div class="text-center py-4">
                                    <button  type="submit" class="btn btn-info">Crear sala <i class="fa fa-paper-plane-o ml-1"></i></button>
                                </div>
                    </form>

                            <!-- Form subscription -->
                        </div>
                    </div>
                </div>


</html>
{% endblock %}

main/templates/PanelAdmin/editarEvento.html
<html>

    <body>

     {% block titulo %}    <h1>Editar evento:</h1>  {% endblock %}

    {% block contenido %}
        <style>
            #login-row {
            background-image: linear-gradient(to bottom, #5ee7df 0%, #b490ca 100%);
            }
        </style>
        {% include 'main/form.html' %}

    {% endblock %}
    </body>

</html>